name: fluintl
description: A Flutter Internationalization support package.Use it to quickly build an international Apps.
version: 0.1.3
author: thl <863764940@qq.com>
homepage: https://github.com/Sky24n/fluintl

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter